# Generated by Django 3.1 on 2021-06-07 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='api_proj_list',
            fields=[
                ('project_key', models.CharField(max_length=80, primary_key=True, serialize=False)),
                ('project_type', models.CharField(blank=True, max_length=255, null=True)),
                ('contract_type', models.CharField(blank=True, max_length=100, null=True)),
                ('summary', models.TextField(blank=True, null=True)),
                ('sub_region', models.TextField(blank=True, null=True)),
                ('proj_status', models.TextField(blank=True, null=True)),
                ('complexity', models.TextField(blank=True, null=True)),
                ('delivery_analyst', models.TextField(blank=True, null=True)),
                ('configuration_analyst', models.TextField(blank=True, null=True)),
                ('production_analyst', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(blank=True, null=True)),
                ('hierarchy_setup_start_date', models.DateTimeField(blank=True, null=True)),
                ('hierarchy_setup_end_date', models.DateTimeField(blank=True, null=True)),
                ('survey_setup_start_date', models.DateTimeField(blank=True, null=True)),
                ('survey_setup_submission_CSD', models.DateTimeField(blank=True, null=True)),
                ('tech_prestest_start_date', models.DateTimeField(blank=True, null=True)),
                ('tech_pretest_end_date', models.DateTimeField(blank=True, null=True)),
                ('survey_lockdown_start_date', models.DateTimeField(blank=True, null=True)),
                ('survey_lockdown_end_date', models.DateTimeField(blank=True, null=True)),
                ('admin_start', models.DateTimeField(blank=True, null=True)),
                ('admin_end', models.DateTimeField(blank=True, null=True)),
                ('mdb_setup_start', models.DateTimeField(blank=True, null=True)),
                ('mdb_submission_date', models.DateTimeField(blank=True, null=True)),
                ('ees_start_date', models.DateTimeField(blank=True, null=True)),
                ('ees_submission_end_date', models.DateTimeField(blank=True, null=True)),
                ('ees_first_results_release_date', models.DateTimeField(blank=True, null=True)),
                ('ees_second_results_release_date', models.DateTimeField(blank=True, null=True)),
                ('da_hours', models.FloatField(blank=True, null=True)),
                ('ca_hours', models.FloatField(blank=True, null=True)),
                ('pa_hours', models.FloatField(blank=True, null=True)),
                ('year', models.IntegerField(blank=True, null=True)),
                ('month', models.CharField(blank=True, max_length=30, null=True)),
                ('standard_hours', models.FloatField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='summaryTable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_analyst_summary', models.TextField(blank=True, null=True)),
                ('project_year', models.IntegerField(blank=True, null=True)),
                ('Jan', models.FloatField(blank=True, null=True)),
                ('Feb', models.FloatField(blank=True, null=True)),
                ('Mar', models.FloatField(blank=True, null=True)),
                ('Apr', models.FloatField(blank=True, null=True)),
                ('May', models.FloatField(blank=True, null=True)),
                ('Jun', models.FloatField(blank=True, null=True)),
                ('Jul', models.FloatField(blank=True, null=True)),
                ('Aug', models.FloatField(blank=True, null=True)),
                ('Sep', models.FloatField(blank=True, null=True)),
                ('Oct', models.FloatField(blank=True, null=True)),
                ('Nov', models.FloatField(blank=True, null=True)),
                ('Dec', models.FloatField(blank=True, null=True)),
                ('project_key_forecast', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='hcbcapacity.api_proj_list')),
            ],
        ),
    ]
