# Generated by Django 3.1 on 2021-06-07 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcbcapacity', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarytable',
            old_name='delivery_analyst_summary',
            new_name='delivery_analyst',
        ),
    ]
