# Generated by Django 3.1 on 2021-06-08 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcbcapacity', '0002_auto_20210607_2007'),
    ]

    operations = [
        migrations.RenameField(
            model_name='summarytable',
            old_name='Apr',
            new_name='apr',
        ),
        migrations.RenameField(
            model_name='summarytable',
            old_name='Aug',
            new_name='aug',
        ),
        migrations.RenameField(
            model_name='summarytable',
            old_name='Dec',
            new_name='dec',
        ),
        migrations.RenameField(
            model_name='summarytable',
            old_name='Feb',
            new_name='feb',
        ),
        migrations.RenameField(
            model_name='summarytable',
            old_name='Jan',
            new_name='jan',
        ),
        migrations.RenameField(
            model_name='summarytable',
            old_name='Jul',
            new_name='jul',
        ),
        migrations.RenameField(
            model_name='summarytable',
            old_name='Jun',
            new_name='jun',
        ),
        migrations.RenameField(
            model_name='summarytable',
            old_name='Mar',
            new_name='mar',
        ),
        migrations.RenameField(
            model_name='summarytable',
            old_name='May',
            new_name='may',
        ),
        migrations.RenameField(
            model_name='summarytable',
            old_name='Nov',
            new_name='nov',
        ),
        migrations.RenameField(
            model_name='summarytable',
            old_name='Oct',
            new_name='oct',
        ),
        migrations.RenameField(
            model_name='summarytable',
            old_name='Sep',
            new_name='sep',
        ),
    ]
