# Generated by Django 3.1 on 2021-06-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcbcapacity', '0003_auto_20210609_0004'),
    ]

    operations = [
        migrations.CreateModel(
            name='std_hours',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month_nm', models.TextField()),
                ('yr', models.IntegerField()),
                ('no_of_hours', models.FloatField()),
            ],
        ),
    ]
