# Generated by Django 3.1 on 2021-08-18 05:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcbcapacity', '0004_std_hours'),
    ]

    operations = [
        migrations.CreateModel(
            name='daProdByMonth',
            fields=[
                ('prod_id', models.IntegerField(primary_key=True, serialize=False)),
                ('delivery_analyst', models.CharField(max_length=100)),
                ('jan', models.FloatField()),
                ('feb', models.FloatField()),
                ('mar', models.FloatField()),
                ('apr', models.FloatField()),
                ('may', models.FloatField()),
                ('jun', models.FloatField()),
                ('jul', models.FloatField()),
                ('aug', models.FloatField()),
                ('sep', models.FloatField()),
                ('oct', models.FloatField()),
                ('nov', models.FloatField()),
                ('dece', models.FloatField()),
            ],
            options={
                'db_table': 'da_prod_by_month',
                'managed': False,
            },
        ),
        migrations.AddField(
            model_name='summarytable',
            name='sub_region',
            field=models.TextField(blank=True, null=True),
        ),
    ]
