# Generated by Django 3.1 on 2021-09-01 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hcbcapacity', '0005_auto_20210818_1355'),
    ]

    operations = [
        migrations.CreateModel(
            name='da_list',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('da_name', models.TextField()),
                ('region', models.TextField()),
            ],
        ),
    ]
