# Generated by Django 3.1 on 2021-09-21 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hcbcapacity', '0006_da_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='api_proj_list',
            old_name='year',
            new_name='project_year',
        ),
    ]
